sudo: required
services:
    - docker
language: go
go:
    - 1.7beta2
before_install:
    - echo -e "machine github.com\n  login $GITHUB_USER\n  password $GITHUB_PASS" >> ~/.netrc
env:
    - TEST_DIR=registry
    - TEST_DIR=rackhd

script:
    - cd $TEST_DIR && make

