#NM_RACKHD

version: "2"

services:
  consulserver:
    image: "skunkworxs/consul:server"
    container_name: "consulserver"
    hostname: "consulserver"
    ports:
      - "8300:8300"
      - "8301:8301"
      - "8301:8301/udp"
      - "8302:8302"
      - "8302:8302/udp"
      - "8400:8400"
      - "8500:8500"
      - "8600:8600"
      - "8600:8600/udp"
    command: "agent -config-dir /etc/consul.d/server.json -bootstrap"
  nm-rackhd-proxy:
    build: .
    image: "skunkworxs/nm-rackhd:latest"
    container_name: "nm-rackhd"
    hostname: "nm-rackhd"
    links:
        - consulclient
    expose:
      - "10001"
      - "10001/udp"
      - "10002"
      - "10002/udp"
      - "8300"
      - "8301"
      - "8301/udp"
      - "8302"
      - "8302/udp"
      - "8400"
      - "8500"
      - "8500/udp"
      - "8600"
      - "8600/udp"
    command: "-proxy-address=http://localhost:10001 -backend-address=consulclient:8500"
    depends_on:
      - consulclient
  ssdpspoofer:
    build: ./cmd/utils
    image: "skunkworxs/endpoint:latest"
    container_name: "endpoint"
    hostname: "endpoint"
    expose:
      - "10002"
      - "10002/udp"
    command: "-endpoint-address=http://localhost:10002 -backend-address=consulclient:8500"
    depends_on:
        - consulclient
  consulclient:
    image: "skunkworxs/consul:client"
    container_name: "consulclient"
    hostname: "consulclient"
    expose:
      - "8300"
      - "8301"
      - "8301/udp"
      - "8302"
      - "8302/udp"
      - "8400"
      - "8500"
      - "8500/udp"
      - "8600"
      - "8600/udp"
    depends_on:
      - consulserver
