#neighborhood-manager
#rackhd

version: "2"

services:
  consulserver:
    image: "rackhd/consul:server"
    container_name: "consulserver"
    hostname: "consulserver"
    expose:
      - "8300"
      - "8301"
      - "8301/udp"
      - "8302"
      - "8302/udp"
      - "8400"
      - "8500"
      - "8600"
      - "8600/udp"
    command: "agent -config-dir /etc/consul.d/server.json -bootstrap"
  nm-rackhd-proxy:
    build:
      context: .
      dockerfile: Dockerfile-proxy
    image: "rackhd/rackhd:latest"
    container_name: "rackhd"
    hostname: "rackhd"
    links:
        - consulclient
    ports:
      - "10001:10001"
    expose:
      - "10001"
      - "10002"
      - "8300"
      - "8301"
      - "8301/udp"
      - "8302"
      - "8302/udp"
      - "8400"
      - "8500"
      - "8500/udp"
      - "8600"
      - "8600/udp"
    command: "-proxy-address=http://0.0.0.0:10001 -backend-address=consulclient:8500 -service-name=RackHD-service:api:2.0:TEST"
    depends_on:
      - consulclient
  endpoint:
    build:
      context: .
      dockerfile: Dockerfile-endpoint
    image: "rackhd/endpoint:latest"
    container_name: "endpoint"
    hostname: "endpoint"
    links:
        - consulclient
    ports:
      - "10002:10002"
    expose:
      - "10001"
      - "10002"
      - "8300"
      - "8301"
      - "8301/udp"
      - "8302"
      - "8302/udp"
      - "8400"
      - "8500"
      - "8500/udp"
      - "8600"
      - "8600/udp"
    command: "-endpoint-address=http://0.0.0.0:10002 -backend-address=consulclient:8500"
    depends_on:
        - consulclient
  consulclient:
    image: "rackhd/consul:client"
    container_name: "consulclient"
    hostname: "consulclient"
    ports:
      - "8500:8500"
    expose:
      - "8300"
      - "8301"
      - "8301/udp"
      - "8302"
      - "8302/udp"
      - "8400"
      - "8500"
      - "8500/udp"
      - "8600"
      - "8600/udp"
    depends_on:
      - consulserver
